# Generated by Django 5.2.6 on 2026-03-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_userprofile_image_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=2, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
